{% set name = "ittapi" %}
{% set version = "3.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: d01825ee713c0cea36c507462a7ce3809909f83068a13114ee38e15a45a4e0b3

build:
  missing_dso_whitelist:
    - "*libstdc++.so*"
    - "*libgcc_s.so*"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - ittapi
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python bindings to Intel Instrumentation and Tracing Technology (ITT) API.
  license: ''
  license_file:

extra:
  recipe-maintainers:
    - mk-srivastava
